In [2]:
pair_count = {(b'e',b's'): 9, (b's', b't'): 9}

max(pair_count, key=lambda pair: (pair_count[pair], pair))


(b's', b't')

In [5]:
for i in range (0):
    print(i)
    

In [ ]:
a = ('a', 'p')
b = ('all', 'b')



('all', 'b')

In [7]:
def reverse_bytes(byte_tuple):
    """Convert each bytes object to tuple of ALL its negative byte values"""
    # return tuple(tuple(-b for b in bytes_obj) for bytes_obj in byte_tuple)
    def negate_bytes(b):
        # Create a tuple that sorts in reverse lexicographic order
        # Pad with positive values to handle length differences
        max_len = 1000  # Longer than any token we'll see
        result = []
        for byte_val in b:
            result.append(-byte_val)
        # Pad with positive values so shorter strings sort AFTER longer ones
        result.extend([1] * (max_len - len(b)))
        return tuple(result)
    
    return tuple(negate_bytes(byte_obj) for byte_obj in byte_tuple)

In [12]:
reverse_bytes((b'a', b'p'))[1]

#reverse_bytes((b'all', b'p'))


(-112,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 

In [13]:
import torch
torch.manual_seed(0)  # Set seed for reproducibility
w = torch.rand(3, 5)
print(w)
o = torch.square(w)
print(o)

o = torch.mean(o, dim=-1)
o.shape

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074],
        [0.6341, 0.4901, 0.8964, 0.4556, 0.6323],
        [0.3489, 0.4017, 0.0223, 0.1689, 0.2939]])
tensor([[2.4627e-01, 5.9016e-01, 7.8283e-03, 1.7432e-02, 9.4509e-02],
        [4.0206e-01, 2.4019e-01, 8.0361e-01, 2.0760e-01, 3.9981e-01],
        [1.2173e-01, 1.6138e-01, 4.9844e-04, 2.8513e-02, 8.6370e-02]])


torch.Size([3])

In [23]:
B, T, C = 2, 4, 3
rms = torch.sqrt(torch.rand(3))


input = torch.rand(B, T, C)


input / rms 




tensor([[[0.3168, 4.4787, 2.1296],
         [0.3639, 2.6470, 2.2011],
         [1.3041, 3.8359, 1.5238],
         [1.0924, 1.1292, 1.5926]],

        [[0.1469, 0.8428, 0.6490],
         [0.9498, 3.8504, 0.5473],
         [0.8515, 4.2536, 1.1730],
         [0.6789, 3.3823, 2.1753]]])

In [27]:
z = torch.empty(5,3)
# 5 row, 4 column


In [ ]:
shape = (B,T,C)

# i want to init a tensor that of shape B,T,C to simulate the swiglu
# the values need to be random between (0,1)
# 
# x = torch.Tensor(shape)
x = torch.rand(B, T, C)

# i want then to create a weight matrix, where the W @ x = 
x


tensor([[[0.8175, 0.9747, 0.4638],
         [0.0508, 0.2630, 0.8405],
         [0.4968, 0.2515, 0.1168],
         [0.0321, 0.0780, 0.3986]],

        [[0.7742, 0.7703, 0.0178],
         [0.8119, 0.1087, 0.3943],
         [0.2973, 0.4037, 0.4018],
         [0.0513, 0.0683, 0.4218]]])

In [33]:
torch.sigmoid(x) # apply to each element

tensor([[[0.6937, 0.7261, 0.6139],
         [0.5127, 0.5654, 0.6986],
         [0.6217, 0.5625, 0.5292],
         [0.5080, 0.5195, 0.5983]],

        [[0.6844, 0.6836, 0.5044],
         [0.6925, 0.5272, 0.5973],
         [0.5738, 0.5996, 0.5991],
         [0.5128, 0.5171, 0.6039]]])

In [34]:
x * torch.sigmoid(x)

tensor([[[0.5671, 0.7077, 0.2848],
         [0.0261, 0.1487, 0.5871],
         [0.3088, 0.1415, 0.0618],
         [0.0163, 0.0405, 0.2385]],

        [[0.5299, 0.5266, 0.0090],
         [0.5622, 0.0573, 0.2355],
         [0.1706, 0.2420, 0.2407],
         [0.0263, 0.0353, 0.2547]]])

In [ ]:
## RoPE
B, T, C = 2, 5, 4
x = torch.rand(B, T, C)
print(x.shape)

d_k = 4
theta = 2
max_seq_len = 16

def angle(k, i, d_k, theta):
    return i / pow(theta, 2*k/d_k)



torch.Size([2, 5, 4])


In [41]:
for i in range ( 1, 2):
    print (i)

1


In [55]:
a = torch.rand((2,3,4))
# print(a)
a - torch.max(a, dim=-1, keepdim=True)[0]

tensor([[[-0.5393, -0.5788,  0.0000, -0.1632],
         [-0.6502, -0.2966, -0.2078,  0.0000],
         [ 0.0000, -0.4630, -0.8291, -0.8400]],

        [[ 0.0000, -0.2458, -0.2489, -0.8995],
         [-0.0107,  0.0000, -0.0222, -0.8955],
         [-0.6621, -0.8174,  0.0000, -0.6883]]])

In [ ]:
a = torch.rand((2,3,4))
weight = torch.rand(4,)

(4, 3)

In [60]:
mask = torch.tril(torch.ones(5, 5), diagonal=0).bool()  # Upper triangular mask
mask

tensor([[ True, False, False, False, False],
        [ True,  True, False, False, False],
        [ True,  True,  True, False, False],
        [ True,  True,  True,  True, False],
        [ True,  True,  True,  True,  True]])

In [13]:
# play with cross entropy
import torch
torch.manual_seed(42)
batch_size = 2
vocab_size = 4
input = torch.rand((batch_size, vocab_size))
targets = torch.randint(0, vocab_size, (batch_size,))

print(input)
print(targets)

# softmax 
from cs336_basics.nn_utils import softmax

logits = softmax(input, 1)
print(logits)
print(targets.unsqueeze(1))

target_log_probs = torch.gather(logits, dim=1, index=targets.unsqueeze(1)).squeeze(1)

target_log_probs = target_log_probs.log()

print(target_log_probs)

loss = -target_log_probs.mean()
print(loss)


print(torch.nn.functional.cross_entropy(input, targets))

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936]])
tensor([2, 1])
tensor([[0.2688, 0.2777, 0.1631, 0.2903],
        [0.2171, 0.2680, 0.1899, 0.3250]])
tensor([[2],
        [1]])
tensor([-1.8132, -1.3168])
tensor(1.5650)
tensor(1.5650)


In [19]:
from collections.abc import Callable, Iterable
from typing import Optional
import torch
import math

class SGD(torch.optim.Optimizer):
    def __init__(self, params, lr=1e-3):
        if lr < 0:
            raise ValueError(f"Invalid learning rate: {lr}")
        defaults = {"lr": lr}
        super().__init__(params, defaults)
    
    def step(self, closure: Optional[Callable] = None):
        loss = None if closure is None else closure()
        for group in self.param_groups:
            lr = group["lr"] # Get the learning rate
        for p in group["params"]:
            if p.grad is None:
                continue
            state = self.state[p] # Get state associated with p.
            t = state.get("t", 0) # Get iteration number from the state, or initial value.
            grad = p.grad.data # Get the gradient of loss with respect to p.
            p.data -= lr / math.sqrt(t + 1) * grad # Update weight tensor in-place.
            state["t"] = t + 1 # Increment iteration number.
        return loss


weights = torch.nn.Parameter(5 * torch.randn((10, 10)))
opt = SGD([weights], lr=1)
for t in range(100):
    opt.zero_grad() # Reset the gradients for all learnable parameters.
    loss = (weights**2).mean() # Compute a scalar loss value.
    print(loss.cpu().item())
    loss.backward() # Run backward pass, which computes gradients.
    opt.step() # Run optimizer step.

29.3043155670166
28.14386558532715
27.353464126586914
26.72541046142578
26.19357681274414
25.727109909057617
25.308700561523438
24.927515029907227
24.57623291015625
24.249643325805664
23.943876266479492
23.65597152709961
23.38360595703125
23.124906539916992
22.87835121154785
22.642675399780273
22.41681480407715
22.199865341186523
21.991056442260742
21.789716720581055
21.595258712768555
21.40717315673828
21.225000381469727
21.04833984375
20.8768310546875
20.71015167236328
20.54800796508789
20.3901309967041
20.23628807067871
20.086257934570312
19.939834594726562
19.79684066772461
19.6571044921875
19.520465850830078
19.38678741455078
19.255929946899414
19.127771377563477
19.002193450927734
18.879093170166016
18.758363723754883
18.639911651611328
18.523651123046875
18.409496307373047
18.29737091064453
18.18720054626465
18.078914642333984
17.972450256347656
17.867738723754883
17.76473045349121
17.663362503051758
17.563587188720703
17.465347290039062
17.368600845336914
17.27330207824707
17.1

In [6]:
from cs336_basics.bpe.Tokenizer import Tokenizer

t = Tokenizer.from_files(vocab_filepath='../tokenizer_output/tiny_head_1000_escape_space/vocab.json',
                     merges_filepath='../tokenizer_output/tiny_head_1000_escape_space/merges.txt' )


test_str = "<endoftext>abcdefg slkj sfjskl lmiwj sdlfa <endoftext> kfsjfla <endoftext>"

print(t._split_on_special_tokens(test_str))

IndexError: list index out of range